=== NoodleNTMY/web/Todo/UD2/AC2.1/lista_de_personas.dtd
<!ELEMENT lista_de_personas (persona*)>
<!ELEMENT persona (nombre,fechanacimiento?,sexo?,numeroseguridadsocial?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechanacimiento (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT numeroseguridadsocial (#PCDATA)>

=== NoodleNTMY/web/Todo/UD2/AC2.1/lista_de_personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_de_persona SYSTEM "lista_de_personas.dtd">
<lista_de_personas>
  <persona>
    <nombre></nombre>
    <fechanacimiento></fechanacimiento>
    <sexo></sexo>
    <numeroseguridadsocial></numeroseguridadsocial>
  </persona>
  <persona>
    <nombre></nombre>
    <fechanacimiento></fechanacimiento>
    <sexo></sexo>
    <numeroseguridadsocial></numeroseguridadsocial>
  </persona>
  <persona>
    <nombre></nombre>
    <fechanacimiento></fechanacimiento>
    <sexo></sexo>
    <numeroseguridadsocial></numeroseguridadsocial>
  </persona>
</lista_de_personas>
